package gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChangelogUI.java
 *
 * Created on Jun 22, 2011, 11:20:03 PM
 */
/**
 * 
 * @author Rodney
 */
public class ChangelogUI extends javax.swing.JDialog {
	private int logIndex = 0;

	/** Creates new form ChangelogUI */
	public ChangelogUI(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();

		setLocation(parent.getLocation().x + 100, parent.getLocation().y + 100);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		nextButton = new javax.swing.JButton();
		previousButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		logArea = new javax.swing.JTextPane();
		logArea.setContentType("text/html");

		logArea.setText(Changelogs.releases[logIndex].getUpdates() + ""
				+ Changelogs.releases[logIndex].getDate());
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Recent changes");

		nextButton.setText("Next");
		nextButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nextButtonActionPerformed(evt);
			}
		});

		previousButton.setText("Previous");
		previousButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				previousButtonActionPerformed(evt);
			}
		});

		logArea.setEditable(false);
		jScrollPane1.setViewportView(logArea);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														380, Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		previousButton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		nextButton)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										249, Short.MAX_VALUE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(nextButton)
												.addComponent(previousButton))
								.addContainerGap()));

		pack();
	}// </editor-fold>

	private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {
		if (logIndex + 1 < Changelogs.releases.length) {
			logIndex++;
		}

		logArea.setText(Changelogs.releases[logIndex].getUpdates() + ""
				+ Changelogs.releases[logIndex].getDate());
	}

	private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {
		if (logIndex - 1 >= 0) {
			logIndex--;
		}

		logArea.setText(Changelogs.releases[logIndex].getUpdates() + ""
				+ Changelogs.releases[logIndex].getDate());
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				ChangelogUI dialog = new ChangelogUI(new javax.swing.JFrame(),
						true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextPane logArea;
	private javax.swing.JButton nextButton;
	private javax.swing.JButton previousButton;
	// End of variables declaration
}
