package gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomMonster.java
 *
 * Created on Jun 22, 2011, 12:18:38 AM
 */
/**
 * 
 * @author Rodney
 */
public class CustomMonsterUI extends javax.swing.JDialog {
	private java.awt.Frame frame;

	/** Creates new form CustomMonster */
	public CustomMonsterUI(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.frame = parent;

		setLocation(parent.getLocation().x + 100, parent.getLocation().y + 100);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		idField = new javax.swing.JTextField();
		nameField = new javax.swing.JTextField();
		addButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Custom");

		idField.setText("Monster Id");

		nameField.setText("Monster name");

		addButton.setText("Add");
		addButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														nameField,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														84, Short.MAX_VALUE)
												.addComponent(
														addButton,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														84, Short.MAX_VALUE)
												.addComponent(
														idField,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														84, Short.MAX_VALUE))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(idField,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(nameField,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(addButton)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {
		DreamFighterUI dui = (DreamFighterUI) frame;
		dui.getMonsterModel().addElement(nameField.getText() + ", id=" + idField.getText() + ", level=" + "0");
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				CustomMonsterUI dialog = new CustomMonsterUI(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton addButton;
	private javax.swing.JTextField idField;
	private javax.swing.JTextField nameField;
	// End of variables declaration
}
